### ISSUE TITLE
In terms of content expansion

### ISSUE THREAD

**Issue by jonyzhang2023** [Tsunami-kun/awesome-humanoid-manipulation#1]
Good work! I was wondering if adding an end effector like a gripper is also a good choice? Because many excellent works nowadays are also done based on dual-arm grippers. Moreover, some 6-degree-of-freedom dexterous hands are essentially grippers. When reinforcement learning is not performed, their methods are almost the same.

**Comment by Tsunami-kun** [comment]
Thank you, and I appreciate for your insightful suggestion! Indeed, and I will be working on such a section :D

**Comment by jonyzhang2023** [comment]
Cool, Let's do a fancy work!
