### ISSUE TITLE
Can LABOR Agent be on the list?

### ISSUE THREAD

**Issue by Kchu** [Tsunami-kun/awesome-humanoid-manipulation#4]
Thanks for organizing the repo for humanoid manipulation papers!
We recently had a new paper accepted in Humanoids 2024, which focuses on using an LLM to orchestrate bimanual hands in long-horizon tasks. It is aligned with the topics here, and the formatted information for reference is as below:
[Humanoids 2024] Large Language Models for Orchestrating Bimanual Robots, [[paper](https://arxiv.org/abs/2404.02018)] [[website](https://labor-agent.github.io/)], [[github](https://github.com/Kchu/LABOR-Agent)]
We would appreciate it if you can put our work on your list. Thank you!

**Comment by Tsunami-kun** [comment]
Of course, and I have added LABOR to the list. Thank you for sharing your work, which is truly inspiring!

**Comment by Kchu** [comment]
Oh, I see it now... the first version came out in April, but the final one was released in October, and the conference will be hosted in November. 
Thank you for your time and effort!

**Comment by Tsunami-kun** [comment]
Yes, the arxiv version date was used... I labeled the dates based on the papers' initial appearance on arxiv, as I feel hard to determine a standard date for papers. Hope this did not cause bias🥲
